version: "3"
  
services:
  server:
    image: gitea/gitea:latest
    network:
      - giteanet
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=dbpostgres
      - GITEA__database__NAME=postgres
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=postgres
    restart: always
    volumes:
      - ./gitea-data:/var/lib/gitea
      - ./gitea-config:/etc/gitea  
    ports:
      - "3000:3000"
      - "1200:1200"
    depends_on:
      - db

  db: 
    image: library/postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./dbgitea-data:/var/lib/postgresql/data
